#!/bin/bash

## Created By Aditya Shakya

MENU="$(rofi -sep "|" -dmenu -i -p 'System' -location 5 -xoffset -14 -yoffset -52 -width 10 -hide-scrollbar -line-padding 4 -padding 20 -lines 4 <<< " Lock| Logout| Suspend|  Reboot| Shutdown")"
            case "$MENU" in
                *Lock) xscreensaver-command -activate ;;
                *Logout) i3-msg exit;;
                *Suspend) systemctl suspend ;;
                *Reboot) systemctl reboot ;;
                *Shutdown) systemctl -i poweroff
            esac
