#!/bin/bash

## Created By Aditya Shakya

MENU="$(rofi -sep "|" -dmenu -i -p 'System' -location 5 -hide-scrollbar <<< " Lock| Logout| Suspend| Reboot| Shutdown")"
            case "$MENU" in
                *Lock) /usr/bin/lock ;;
                *Logout) i3-msg exit;;
                *Suspend) systemctl suspend ;;
                *Reboot) systemctl reboot ;;
                *Shutdown) systemctl -i poweroff
            esac
