---
- hosts: localhost
  become: true
  become_user: "{{user}}"
  tasks:
    - include: tasks/packages.yml
    - include: tasks/go.yml
    - include: tasks/neovim.yml
    - include: tasks/zsh.yml
    - include: tasks/i3-gaps.yml
