---
- hosts: localhost
  become: true
  become_user: "{{user}}"
  tasks:
    - include: tasks/packages.yml
    - include: tasks/go.yml
    - include: tasks/node.yml
    - include: tasks/neovim.yml
    - include: tasks/zsh.yml
    - include: tasks/fonts.yml
    - include: tasks/i3-gaps.yml
    - include: tasks/termite.yml
    - include: tasks/polybar.yml
    - include: tasks/user.yml
