---
- hosts: localhost
  become: true
  become_user: "{{user}}"
  environment:
    PATH: "/opt/node/bin:{{ ansible_env.PATH }}"
  tasks:
    - include: tasks/debug.yml
    - include: tasks/packages.yml
    - include: tasks/node.yml
    - include: tasks/termite.yml
    - include: tasks/zsh.yml
    - include: tasks/neovim.yml
    - include: tasks/fonts.yml
    - include: tasks/i3-gaps.yml
    - include: tasks/polybar.yml
    - include: tasks/user.yml
    - include: tasks/conky.yml
    - include: tasks/scripts.yml
    - include: tasks/configs.yml
