---
- hosts: localhost
  become: true
  vars:
    home: "{{ lookup('env','DESTINATION') }}"
  tasks:
    - include: tasks/packages.yml
    - include: tasks/neovim.yml
    - include: tasks/i3-gaps.yml
