---
- hosts: localhost
  become: true
  become_user: "{{user}}"
  environment:
    PATH: "/opt/node/bin:{{ ansible_env.PATH }}"
  tasks:
    - import_tasks: tasks/debug.yml
    - import_tasks: themes/molokai.yml
    - import_tasks: themes/paper.yml
    - import_tasks: themes/clean_red.yml
    - import_tasks: themes/dark_red.yml
    - import_tasks: themes/default.yml
    - import_tasks: themes/simple.yml
    - import_tasks: tasks/packages.yml
    - import_tasks: tasks/node.yml
    - import_tasks: tasks/terminator.yml
    - import_tasks: tasks/zsh.yml
    - import_tasks: tasks/neovim.yml
    - import_tasks: tasks/fonts.yml
    - import_tasks: tasks/i3-gaps.yml
    - import_tasks: tasks/polybar.yml
    - import_tasks: tasks/rofi.yml
    - import_tasks: tasks/conky.yml
    - import_tasks: tasks/scripts.yml
    - import_tasks: tasks/bin.yml
    - import_tasks: tasks/configs.yml
    - import_tasks: tasks/flutter.yml
    - import_tasks: tasks/wezterm.yml
