---
- name: "[Fedora] Install alacritty"
  become_user: root
  dnf:
    name:
      - alacritty
    state: latest
  when: ansible_distribution == 'Fedora'
- name: copy alacritty config
  copy: src=config/alacritty/{{theme}}/alacritty.yml dest={{destination}}/.alacritty owner={{user}} mode=0664
