---
- name: Copy scripts bin files
  become_user: root
  copy:
    src: "bin/{{item}}"
    dest: "/usr/bin/{{item}}"
    mode: "755"
  with_items:
    - lock
    - status-bar
    - set_playback
    - unset_playback
