---
- name: Install i3-gaps from negativo
  become_user: root
  dnf:
    name:
      - conky
      - jq
    state: latest
- name: Copy Conky Configs
  copy: src=config/conky dest={{destination}}/.config owner={{user}} group={{user}}
- name: Change conky scripts permission
  command: "chmod +x {{destination}}/.config/conky/{{item}}"
  with_items:
    - start
