---
- name: "[Fedora] Install i3-gaps from negativo"
  become_user: root
  dnf:
    name:
      - conky
      - jq
    state: latest
  when: ansible_distribution == 'Fedora'
- name: "[Manjaro] Install i3-gaps from negativo"
  become_user: root
  pacman:
    name:
      - conky
      - jq
    state: present
  when: ansible_distribution == 'Manjaro'
- name: Copy Conky Configs
  copy: src=config/conky dest={{destination}}/.config owner={{user}} group={{user}}
- name: Change conky scripts permission
  command: "chmod +x {{destination}}/.config/conky/{{item}}"
  with_items:
    - start
