---
- name: "Ansible Distribution"
  debug:
    msg: "The operating system is {{ ansible_distribution }} {{ ansible_distribution_major_version }}"
- name: "Selected theme"
  debug:
    msg: "The current theme is {{ theme }}"
- name: "Main monitor"
  debug:
    msg: "{{ main_monitor }}"
- name: "Optional Tasks"
  debug:
    msg: "{{ optional_tasks }}"
  when: optional_tasks is defined
