---
- name: Creates fonts directory
  file:
    path: "{{destination}}/.fonts"
    state: directory
- name: Copy fonts
  copy:
    src: "fonts/{{item}}"
    dest: "{{destination}}/.fonts"
  with_items:
    - FantasqueSansMono-Bold.ttf
    - FantasqueSansMono-BoldItalic.ttf
    - FantasqueSansMono-Italic.ttf
    - FantasqueSansMono-Regular.ttf
    - icomoon-feather.ttf
    - waffle-10.bdf
    - MesloLGS NF Bold Italic.ttf
    - MesloLGS NF Bold.ttf
    - MesloLGS NF Italic.ttf
    - MesloLGS NF Regular.ttf
