---
- name: "[Fedora] Install Go Lang Packages"
  become_user: root
  dnf:
    name:
      - golang
    state: latest
  when: ansible_distribution == 'Fedora'
- name: "[Archlinux] Install Go Lang Packages"
  become_user: root
  pacman:
    name:
      - go
    state: present
  when: ansible_distribution == 'Archlinux'
