---
- name: "[Fedora] Install i3-gaps dependencies"
  become_user: root
  dnf:
    name:
      - cairo-devel
      - libev
      - libev-devel
      - libjpeg-devel
      - libjpeg-turbo
      - libxcb
      - libxkbcommon
      - libxkbcommon-x11
      - libxkbcommon-x11-devel
      - pam-devel
      - pkg-config
      - xcb-util-devel
      - xcb-util-image
      - xcb-util-image-devel
      - startup-notification
      - startup-notification-devel
      - xcb-util-cursor-devel
      - xcb-util-keysyms-devel
      - xcb-util-wm-devel
      - xcb-util-xrm-devel
      - yajl
      - yajl-devel
      - compton
      - dunst
      - maim
    state: latest
  when: ansible_distribution == 'Fedora'
- name: "[Ubuntu] Install i3-gaps"
  become_user: root
  apt:
    update_cache: yes
    pkg:
      - compton
      - dunst
      - maim
      - feh
      - rofi
      - ninja-build
      - meson
      - libstartup-notification0
      - libstartup-notification0-dev
      - libxcb-xinerama0
      - libxcb-xinerama0-dev
      - libxcb-cursor0
      - libxcb-cursor-dev
      - libxcb-keysyms1
      - libxcb-keysyms1-dev
      - libxcb1-dev
      - libpango1.0-dev
      - libxcb-util0-dev
      - libxcb-icccm4-dev
      - libyajl-dev
      - libxcb-randr0-dev
      - libev-dev
      - libxcb-xkb-dev
      - libxkbcommon-dev
      - libxkbcommon-x11-dev
      - xutils-dev
      - libtool
      - libxcb-shape0-dev
    state: latest
  when: ansible_distribution == 'Ubuntu'
- name: Clone i3-gaps repository
  git:
    repo: 'https://github.com/Airblader/i3.git'
    dest: /tmp/i3
- name: copy i3 build script
  copy: src=build/build-i3.sh dest=/tmp/i3 owner={{user}} mode=0774
- name: Make and Install i3-gaps
  become_user: root
  command: "/tmp/i3/build-i3.sh"
- name: Install Flashfocus
  become_user: root
  pip:
    name: flashfocus
- name: Install i3-resurrect
  become_user: root
  pip:
    name: i3-resurrect
- name: Creates i3 config directory
  file:
    path: "{{destination}}/.config/i3"
    state: directory
- name: Creates dunst config directory
  file:
    path: "{{destination}}/.config/dunst"
    state: directory
- name: copy i3 config
  template:
    src: config/i3/config.j2
    dest: "{{destination}}/.config/i3/config"
  tags:
    - configs
    - i3
- name: copy i3 compton.conf
  copy: src=config/i3/compton.conf dest={{destination}}/.config/i3/compton.conf owner={{user}} mode=0664
- name: copy dunst config
  template:
    src: config/dunst/config.j2
    dest: "{{destination}}/.config/dunst/config"
