---
- name: Enable Fedora Copr for i3-gaps
  become_user: root
  command: "dnf copr enable -y nforro/i3-gaps"
- name: Install i3-gaps
  become_user: root
  dnf:
    name:
      - i3-gaps
      - compton
      - dunst
      - scrot
      - feh
      - rofi
      - xscreensaver
    state: latest
- name: Install Flashfocus
  become_user: root
  pip:
    name: flashfocus
- name: Creates i3 config directory
  file:
    path: "{{destination}}/.config/i3"
    state: directory
- name: Creates dunst config directory
  file:
    path: "{{destination}}/.config/dunst"
    state: directory
- name: copy i3 config
  template:
    src: config/i3/config.j2
    dest: "{{destination}}/.config/i3/config"
- name: copy i3 compton.conf
  copy: src=config/i3/compton.conf dest={{destination}}/.config/i3/compton.conf owner={{user}} group={{user}} mode=0664
- name: copy i3 wallpaper
  copy: src=config/wallpapers dest={{destination}}/.config owner={{user}} group={{user}}
- name: copy dunst config
  copy: src=config/dunst/config dest={{destination}}/.config/dunst/config owner={{user}} group={{user}} mode=0664
