---
- name: "[Fedora] Enable Fedora Copr for i3-gaps"
  become_user: root
  command: "dnf copr enable -y nforro/i3-gaps"
  when: ansible_distribution == 'Fedora' 
- name: "[Fedora] Install i3-gaps"
  become_user: root
  dnf:
    name:
      - i3-gaps
      - compton
      - dunst
      - scrot
      - feh
      - rofi
      - cairo-devel
      - libev
      - libev-devel
      - libjpeg-devel
      - libjpeg-turbo
      - libxcb
      - libxkbcommon
      - libxkbcommon-x11
      - libxkbcommon-x11-devel
      - pam-devel
      - pkg-config
      - xcb-util-devel
      - xcb-util-image
      - xcb-util-image-devel
    state: latest
  when: ansible_distribution == 'Fedora' 
- name: "[Archlinux] Install i3-gaps"
  become_user: root
  pacman:
    name:
      - i3-gaps
      - compton
      - dunst
      - scrot
      - feh
      - rofi
      - libev
      - xcb-util-xrm
    state: present
  when: ansible_distribution == 'Archlinux' 
- name: Install Flashfocus
  become_user: root
  pip:
    name: flashfocus
    extra_args: --user
- name: Creates i3 config directory
  file:
    path: "{{destination}}/.config/i3"
    state: directory
- name: Creates dunst config directory
  file:
    path: "{{destination}}/.config/dunst"
    state: directory
- name: copy i3 config
  template:
    src: config/i3/config.j2
    dest: "{{destination}}/.config/i3/config"
- name: copy i3 compton.conf
  copy: src=config/i3/compton.conf dest={{destination}}/.config/i3/compton.conf owner={{user}} group={{user}} mode=0664
- name: copy i3 wallpaper
  copy: src=config/wallpapers dest={{destination}}/.config owner={{user}} group={{user}}
- name: copy dunst config
  copy: src=config/dunst/config dest={{destination}}/.config/dunst/config owner={{user}} group={{user}} mode=0664
- name: Clone i3lock-color repository
  git:
    repo: 'https://github.com/PandorasFox/i3lock-color.git'
    dest: /tmp/i3lock-color
- name: copy i3lock build script
  copy: src=build/build-i3lock-color.sh dest=/tmp/i3lock-color owner={{user}} group={{user}} mode=0774
- name: Make and Install i3lock-color
  become_user: root
  command: "/tmp/i3lock-color/build-i3lock-color.sh"
- name: Install lock script
  become_user: root
  copy: src=bin/lock dest=/usr/bin/lock mode=0775
