---
- name: Enable Fedora Copr for NeoVim
  command: "dnf copr enable -y nforro/i3-gaps"
- name: Install i3-gaps from negativo
  dnf:
    name:
      - i3-gaps
      - compton
      - feh
      - xscreensaver
    state: latest
- name: copy i3 config
  copy: src=config/i3/config dest={{destination}}/.config/i3 owner={{user}} group={{user}} mode=0664
- name: copy i3 compton.conf
  copy: src=config/i3/compton.conf dest={{destination}}/.config/i3 owner={{user}} group={{user}} mode=0664
