---
- name: "[Fedora] Enable Fedora Copr for i3-gaps"
  become_user: root
  command: "dnf copr enable -y nforro/i3-gaps"
  when: ansible_distribution == 'Fedora' 
- name: "[Fedora] Install i3-gaps"
  become_user: root
  dnf:
    name:
      - i3-gaps
      - compton
      - dunst
      - maim
      - feh
      - rofi
      - cairo-devel
      - libev
      - libev-devel
      - libjpeg-devel
      - libjpeg-turbo
      - libxcb
      - libxkbcommon
      - libxkbcommon-x11
      - libxkbcommon-x11-devel
      - pam-devel
      - pkg-config
      - xcb-util-devel
      - xcb-util-image
      - xcb-util-image-devel
      - meld
    state: latest
  when: ansible_distribution == 'Fedora'
- name: Install Flashfocus
  become_user: root
  pip:
    name: flashfocus
- name: Creates i3 config directory
  file:
    path: "{{destination}}/.config/i3"
    state: directory
- name: Creates dunst config directory
  file:
    path: "{{destination}}/.config/dunst"
    state: directory
- name: copy i3 config
  template:
    src: config/i3/config.j2
    dest: "{{destination}}/.config/i3/config"
- name: copy i3 compton.conf
  copy: src=config/i3/compton.conf dest={{destination}}/.config/i3/compton.conf owner={{user}} group={{user}} mode=0664
- name: copy dunst config
  copy: src=config/dunst/config dest={{destination}}/.config/dunst/config owner={{user}} group={{user}} mode=0664
