---
- name: "[Fedora] Install i3-gaps dependencies"
  become_user: root
  dnf:
    name:
      - cairo-devel
      - libev
      - libev-devel
      - libjpeg-devel
      - libjpeg-turbo
      - libxcb
      - libxkbcommon
      - libxkbcommon-x11
      - libxkbcommon-x11-devel
      - pam-devel
      - pkg-config
      - xcb-util-devel
      - xcb-util-image
      - xcb-util-image-devel
      - startup-notification
      - startup-notification-devel
      - xcb-util-cursor-devel
      - xcb-util-keysyms-devel
      - xcb-util-wm-devel
      - xcb-util-xrm-devel
      - yajl
      - yajl-devel
    state: latest
  when: ansible_distribution == 'Fedora'
- name: Clone i3-gaps repository
  git:
    repo: 'https://github.com/Airblader/i3.git'
    dest: /tmp/i3
  when: ansible_distribution == 'Fedora'
- name: copy i3 build script
  copy: src=build/build-i3.sh dest=/tmp/i3 owner={{user}} mode=0774
  when: ansible_distribution == 'Fedora'
- name: Make and Install i3-gaps
  become_user: root
  command: "/tmp/i3/build-i3.sh"
  when: ansible_distribution == 'Fedora'
- name: "[Ubuntu] Install ppa to i3-gaps"
  become_user: root
  apt_repository:
    repo: ppa:kgilmer/speed-ricer
  when: ansible_distribution == 'Ubuntu'
- name: "[Ubuntu] Install i3-gaps"
  become_user: root
  apt:
    update_cache: yes
    pkg:
      - i3-gaps
      - compton
      - dunst
      - maim
      - feh
      - rofi
    state: latest
  when: ansible_distribution == 'Ubuntu'
- name: Install Flashfocus
  become_user: root
  pip:
    name: flashfocus
- name: Install i3-resurrect
  become_user: root
  pip:
    name: i3-resurrect
- name: Creates i3 config directory
  file:
    path: "{{destination}}/.config/i3"
    state: directory
- name: Creates dunst config directory
  file:
    path: "{{destination}}/.config/dunst"
    state: directory
- name: copy i3 config
  template:
    src: config/i3/config.j2
    dest: "{{destination}}/.config/i3/config"
- name: copy i3 compton.conf
  copy: src=config/i3/compton.conf dest={{destination}}/.config/i3/compton.conf owner={{user}} mode=0664
- name: copy dunst config
  template:
    src: config/dunst/config.j2
    dest: "{{destination}}/.config/dunst/config"
