---
- name: Create NeoVim Base
  command: "mkdir -p {{destination}}/.config/nvim/"
- name: Install Plug for NeoVim Plugins
  command: "curl -fLo {{destination}}/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
- name: copy init.vim
  copy: src=config/nvim/init.vim dest={{destination}}/.config/nvim owner={{user}} group={{user}} mode=0664
- pip:
    name: neovim
    extra_args: --user
- name: Install NeoVim Plugins
  shell: >
    nvim
    +PlugInstall
    +UpdateRemotePlugins
    +qall!
