---
- name: "[Fedora] Enable Fedora Copr for NeoVim"
  become_user: root
  command: "dnf copr enable -y agriffis/neovim-nightly"
  when: ansible_distribution == 'Fedora'
  tags:
    - nvim
- name: "[Fedora] Install NeoVim from negativo"
  become_user: root
  dnf:
    name:
      - neovim
    state: latest
  when: ansible_distribution == 'Fedora'
  tags:
    - nvim
- name: "[Ubuntu] Install ppa to neovim"
  become_user: root
  apt_repository:
    repo: ppa:neovim-ppa/stable
  when: ansible_distribution == 'Ubuntu'
  tags:
    - nvim
- name: "[Ubuntu] Install neovim from ppa"
  become_user: root
  apt:
    update_cache: yes
    pkg:
      - neovim
    state: latest
  when: ansible_distribution == 'Ubuntu'
  tags:
    - nvim
- pip:
    name: neovim
    extra_args: --user
- name: Check for packer installation
  stat: path=~/.local/share/nvim/site/pack/packer/start/packer.nvim
  register: packer
  tags:
    - nvim
- name: Install Packer for NeoVim Plugins
  command: "git clone https://github.com/wbthomason/packer.nvim ~/.local/share/nvim/site/pack/packer/start/packer.nvim"
  when: not packer.stat.exists
  tags:
    - nvim
- name: Create New NeoVim Base
  command: "mkdir -p {{destination}}/.config/nvim/lua"
  tags:
    - nvim
- name: copy init.vim
  copy: src=config/nvim/init.vim dest={{destination}}/.config/nvim/init.vim owner={{user}} mode=0664
  tags:
    - nvim
- name: copy lua files
  copy:
    src: "config/nvim/lua/{{item}}"
    dest: "{{destination}}/.config/nvim/lua"
  with_items:
    - plugins.lua
    - gitsigns-config.lua
    - languages-configs.lua
    - todo-comments-configs.lua
    - autocomplete.lua
    - bufferline-config.lua
    - lualine-configs.lua
    - mutmut-configs.lua
    - nose2coverage-configs.lua
    - theme.lua
    - octo-configs.lua
    - tree.lua
    - twilight-configs.lua
    - ui-configs.lua
  tags:
    - nvim
