---
- name: Enable Fedora Copr for NeoVim
  command: "dnf copr enable -y agriffis/neovim-nightly"
- name: Install NeoVim from negativo
  dnf:
    name:
      - neovim
    state: latest
- name: Install Plug for NeoVim Plugins
  command: "curl -fLo {{ home }}/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
