---
- name: "[Fedora] Enable Fedora Copr for NeoVim"
  become_user: root
  command: "dnf copr enable -y agriffis/neovim-nightly"
  when: ansible_distribution == 'Fedora'
  tags:
    - nvim
- name: "[Fedora] Install NeoVim from negativo"
  become_user: root
  dnf:
    name:
      - neovim
    state: latest
  when: ansible_distribution == 'Fedora'
  tags:
    - nvim
- name: "[Ubuntu] Check for neovim installation"
  stat: path=/opt/nvim.appimage-0.9.0
  register: neovim
  when: ansible_distribution == 'Ubuntu'
- name: "[Ubuntu] download neovim app image"
  become_user: root
  command: "curl -fLo /opt/nvim.appimage-0.9.0 https://github.com/neovim/neovim/releases/download/v0.9.0/nvim.appimage && chmod +x /opt/nvim.appimage-0.9.0"
  when: ansible_distribution == 'Ubuntu'
- name: "[Ubuntu] create link"
  become_user: root
  command: "ln -s /opt/nvim.appimage-0.9.0 /usr/bin/nvim"
  when: ansible_distribution == 'Ubuntu'
- pip:
    name: neovim
    extra_args: --user
- name: Check for packer installation
  stat: path=~/.local/share/nvim/site/pack/packer/start/packer.nvim
  register: packer
  tags:
    - nvim
- name: Install Packer for NeoVim Plugins
  command: "git clone https://github.com/wbthomason/packer.nvim ~/.local/share/nvim/site/pack/packer/start/packer.nvim"
  when: not packer.stat.exists
  tags:
    - nvim
- name: Create New NeoVim Base
  command: "mkdir -p {{destination}}/.config/nvim/lua"
  tags:
    - nvim
- name: copy init.vim
  copy: src=config/nvim/init.vim dest={{destination}}/.config/nvim/init.vim owner={{user}} mode=0664
  tags:
    - nvim
- name: copy lua files
  copy:
    src: "config/nvim/lua/{{item}}"
    dest: "{{destination}}/.config/nvim/lua"
  with_items:
    - plugins.lua
    - gitsigns-config.lua
    - languages-configs.lua
    - todo-comments-configs.lua
    - autocomplete.lua
    - bufferline-config.lua
    - lualine-configs.lua
    - mutmut-configs.lua
    - nose2coverage-configs.lua
    - theme.lua
    - octo-configs.lua
    - tree.lua
    - twilight-configs.lua
    - ui-configs.lua
    - ai-configs.lua
  tags:
    - nvim
