---
- name: "[Fedora] Enable Fedora Copr for NeoVim"
  become_user: root
  command: "dnf copr enable -y agriffis/neovim-nightly"
  when: ansible_distribution == 'Fedora' 
- name: "[Fedora] Install NeoVim from negativo"
  become_user: root
  dnf:
    name:
      - neovim
    state: latest
  when: ansible_distribution == 'Fedora' 
- name: "[Archlinux] Install NeoVim"
  become_user: root
  dnf:
    name:
      - neovim
    state: present
  when: ansible_distribution == 'Archlinux' 
- name: Create NeoVim Base
  command: "mkdir -p {{destination}}/.config/nvim/"
- name: Install Plug for NeoVim Plugins
  command: "curl -fLo {{destination}}/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
- name: copy init.vim
  copy: src=config/nvim/init.vim dest={{destination}}/.config/nvim owner={{user}} group={{user}} mode=0664
- pip:
    name: neovim
- name: Install NeoVim Plugins
  shell: >
    vim
    +PlugInstall
    +UpdateRemotePlugins
    +qall!
