---
- name: Enable Fedora Copr for NeoVim
  command: "dnf copr enable -y agriffis/neovim-nightly"
- name: Install NeoVim from negativo
  dnf:
    name:
      - neovim
    state: latest
- name: Create NeoVim Base
  command: "mkdir -p {{destination}}/.config/nvim/"
- name: Install Plug for NeoVim Plugins
  command: "curl -fLo {{destination}}/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
- name: Change Permissions of NeoVim Base
  command: "chown -R {{user}} {{destination}}/.config/nvim/ {{destination}}/.local/share/nvim/"
- name: copy init.vim
  copy: src=config/nvim/init.vim dest={{destination}}/.config/nvim owner={{user}} group={{user}} mode=0664
- pip:
    name: neovim
