---
- name: Check for node installation
  stat: path={{destination}}/.pkgs/node
  register: node
- name: Download Node
  command: "curl -fLo {{destination}}/.pkgs/node.tar.xz https://nodejs.org/dist/v12.6.0/node-v12.6.0-linux-x64.tar.xz"
  when: not node.stat.exists
- name: Extract Node
  command: "tar xf {{destination}}/.pkgs/node.tar.xz -C {{destination}}/.pkgs"
  when: not node.stat.exists
- name: Create Link for Node
  command: "ln -s {{destination}}/.pkgs/node-v12.6.0-linux-x64 {{destination}}/.pkgs/node"
  when: not node.stat.exists
