---
- name: "[Fedora] download free"
  command: "curl -fLo /tmp/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
  when: ansible_distribution == 'Fedora'
- name: "[Fedora] Enable the RPM Fusion repository free"
  become_user: root
  command: "dnf install -y /tmp/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
  when: ansible_distribution == 'Fedora'
- name: "[Fedora] download free"
  command: "curl -fLo /tmp/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
  when: ansible_distribution == 'Fedora'
- name: "[Fedora] Enable the RPM Fusion repository nonfree"
  become_user: root
  command: "dnf install -y /tmp/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
  when: ansible_distribution == 'Fedora'
- name: "[Fedora] Update System"
  become_user: root
  dnf:
    name: "*"
    state: latest
  when: ansible_distribution == 'Fedora'
- name: "[Fedora] Install System Packages"
  become_user: root
  dnf:
    name:
      - htop
      - powerline-fonts
      - tidy
      - autoconf
      - gitk
      - xscreensaver
      - cmake
      - gcc-c++
      - astyle
      - conky
      - xdotool
      - pavucontrol
      - automake
      - python3-devel
      - python3-pip
      - gtkmm30-devel
      - sqlite-devel
      - libnotify-devel
      - intltool
      - boost-devel
      - blueman
      - cppcheck
      - uncrustify
      - ripgrep
      - meld
      - aspell
      - aspell-pt_BR
      - meson
      - rofi
      - perl-ExtUtils-MakeMaker
      - feh
      - playerctl
      - xfce4-notifyd
      - lua-filesystem
      - lua5.1-filesystem
      - kubernetes-client
      - fzf
      - libevent-devel
      - pcre-devel
      - terraform-ls
    state: latest
  when: ansible_distribution == 'Fedora'
- name: "[Ubuntu] Install System Packages"
  become_user: root
  apt:
    update_cache: yes
    pkg:
      - htop
      - fonts-powerline
      - tidy
      - autoconf
      - gitk
      - xscreensaver
      - cmake
      - build-essential
      - g++
      - astyle
      - conky
      - xdotool
      - pavucontrol
      - automake
      - libgtkmm-3.0-dev
      - libsqlite3-dev
      - libnotify-dev
      - intltool
      - blueman
      - cppcheck
      - uncrustify
      - meld
      - aspell
      - aspell-pt-br
      - python3-pip
      - xfce4-notifyd
    state: latest
  when: ansible_distribution == 'Ubuntu'
