---
- name: "[Fedora] Update System"
  become_user: root
  dnf:
    name: "*"
    state: latest
  when: ansible_distribution == 'Fedora'
- name: "[Fedora] Install System Packages"
  become_user: root
  dnf:
    name:
      - htop
      - powerline-fonts
      - tidy
    state: latest
  when: ansible_distribution == 'Fedora'
- name: "[Archlinux] Install System Packages"
  become_user: root
  pacman:
    name:
      - htop
      - powerline-fonts
      - tidy
    state: present
  when: ansible_distribution == 'Archlinux'
