- name: "[Fedora] Update System"
  become_user: root
  dnf:
    name: "*"
    state: latest
  when: ansible_distribution == 'Fedora'
- name: "[Fedora] Install System Packages"
  become_user: root
  dnf:
    name:
      - htop
      - powerline-fonts
      - tidy
      - autoconf
      - gitk
      - xscreensaver
    state: latest
  when: ansible_distribution == 'Fedora'
