- name: "[Fedora] Update System"
  become_user: root
  dnf:
    name: "*"
    state: latest
  when: ansible_distribution == 'Fedora'
- name: "[Fedora] Install System Packages"
  become_user: root
  dnf:
    name:
      - htop
      - powerline-fonts
      - tidy
      - autoconf
      - gitk
      - xscreensaver
      - cmake
      - gcc-c++
      - astyle
      - conky
      - xdotool
      - pavucontrol
      - automake
      - python3-devel
      - gtkmm30-devel
      - sqlite-devel
      - libnotify-devel
      - intltool
      - boost-devel
      - blueman
      - cppcheck
      - uncrustify
    state: latest
  when: ansible_distribution == 'Fedora'
