---
- name: Update System
  become_user: root
  dnf:
    name: "*"
    state: latest
- name: Install System Packages
  become_user: root
  dnf:
    name:
      - htop
      - powerline-fonts
      - tidy
    state: latest
