---
- name: "[Fedora] Enable the RPM Fusion repository free"
  become_user: root
  dnf:
    name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm"
    state: present
  when: ansible_distribution == 'Fedora'
- name: "[Fedora] Enable the RPM Fusion repository nonfree"
  become_user: root
  dnf:
    name: "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ansible_distribution_major_version}}.noarch.rpm"
    state: present
  when: ansible_distribution == 'Fedora'
- name: "[Fedora] Update System"
  become_user: root
  dnf:
    name: "*"
    state: latest
  when: ansible_distribution == 'Fedora'
- name: "[Fedora] Install System Packages"
  become_user: root
  dnf:
    name:
      - htop
      - powerline-fonts
      - tidy
      - autoconf
      - gitk
      - xscreensaver
      - cmake
      - gcc-c++
      - astyle
      - conky
      - xdotool
      - pavucontrol
      - automake
      - python3-devel
      - gtkmm30-devel
      - sqlite-devel
      - libnotify-devel
      - intltool
      - boost-devel
      - blueman
      - cppcheck
      - uncrustify
      - ripgrep
      - meld
      - aspell
      - aspell-pt_BR
    state: latest
  when: ansible_distribution == 'Fedora'
- name: "[Ubuntu] Install System Packages"
  become_user: root
  apt:
    update_cache: yes
    pkg:
      - htop
      - fonts-powerline
      - tidy
      - autoconf
      - gitk
      - xscreensaver
      - cmake
      - build-essential
      - g++
      - astyle
      - conky
      - xdotool
      - pavucontrol
      - automake
      - python3-dev
      - python3-pip
      - python-pip
      - libgtkmm-3.0-dev
      - libsqlite3-dev
      - libnotify-dev
      - intltool
      - libboost1.65-all-dev
      - blueman
      - cppcheck
      - uncrustify
      - meld
      - aspell
      - aspell-pt-br
    state: latest
  when: ansible_distribution == 'Ubuntu'
