---
- name: Update System
  become_user: root
  dnf:
    name: "*"
    state: latest
- name: Install System Packages
  become_user: root
  dnf:
    name:
      - htop
      - terminator
    state: latest
- name: Creates pkg directory
  file:
    path: "{{destination}}/.pkgs"
    state: directory
