---
- name: Install dependencies for polybar
  become_user: root
  dnf:
    name:
      - make
      - cmake
      - gcc-c++
      - cairo-devel
      - libcurl-devel
      - alsa-lib-devel
      - libmpd-devel
      - mpc
      - pulseaudio-libs-devel
      - xcb-proto
      - python2-devel
      - libmpdclient
      - libmpdclient-devel
      - wireless-tools
      - wireless-tools-devel
      - xcb-util-devel
      - xcb-util-wm-devel
      - xcb-util-cursor-devel
      - xcb-util-xrm-devel
    state: latest
- name: Clone polybar repository
  git:
    repo: 'https://github.com/polybar/polybar.git'
    dest: /tmp/polybar
- name: copy polybar build script
  copy: src=build/build-polybar.sh dest=/tmp/polybar owner={{user}} group={{user}} mode=0774
- name: Make and Install Polybar
  become_user: root
  command: "/tmp/polybar/build-polybar.sh"
- name: Copy Rofi Configs
  copy: src=config/rofi dest={{destination}}/.config owner={{user}} group={{user}}
- name: Copy Polybar Configs
  copy: src=config/polybar dest={{destination}}/.config owner={{user}} group={{user}}
- name: Copy Launcher Script
  copy: src=config/polybar/launch.sh dest={{destination}}/.config/polybar owner={{user}} group={{user}} mode=0774
- name: Change scripts permission
  command: "chmod +x {{destination}}/.config/polybar/scripts/{{item}}"
  with_items:
    - lyrics
    - powermenu
    - translate_lyrics
