---
- name: "[Fedora] Install polybar"
  become_user: root
  dnf:
    name:
      - polybar
    state: latest
  when: ansible_distribution == 'Fedora'
- name: "[Ubuntu] Install dependencies for polybar"
  become_user: root
  apt:
    update_cache: yes
    pkg:
      - cmake
      - cmake-data
      - libcairo2-dev
      - libxcb1-dev
      - libxcb-ewmh-dev
      - libxcb-icccm4-dev
      - libxcb-image0-dev
      - libxcb-randr0-dev
      - libxcb-util0-dev
      - libxcb-xkb-dev
      - libxcb-composite0-dev
      - pkg-config
      - python-xcbgen
      - xcb-proto
      - libxcb-xrm-dev
      - libasound2-dev
      - libmpdclient-dev
      - libiw-dev
      - libcurl4-openssl-dev
      - libpulse-dev
      - libjsoncpp1
      - libjsoncpp-dev
    state: latest
  when: ansible_distribution == 'Ubuntu'
- name: Install lyrics package globally.
  become_user: root
  npm:
    name: lyrics-cli
    global: true
- name: Clone polybar repository
  git:
    repo: 'https://github.com/polybar/polybar.git'
    dest: /tmp/polybar
  when: ansible_distribution == 'Ubuntu'
- name: copy polybar build script
  copy: src=build/build-polybar.sh dest=/tmp/polybar owner={{user}} mode=0774
  when: ansible_distribution == 'Ubuntu'
- name: Make and Install Polybar
  become_user: root
  command: "/tmp/polybar/build-polybar.sh"
  when: ansible_distribution == 'Ubuntu'
- name: Copy Polybar Configs
  copy: src=config/polybar/{{machine}}/ dest={{destination}}/.config/polybar/ owner={{user}}
  tags:
    - configs
    - polybar
- name: copy polybar default colors
  template:
    src: config/polybar/{{machine}}/default/colors.ini.j2
    dest: "{{destination}}/.config/polybar/default/colors.ini"
  tags:
    - configs
    - polybar
- name: copy polybar top menu
  template:
    src: config/polybar/{{machine}}/default/top.ini.j2
    dest: "{{destination}}/.config/polybar/default/top.ini"
  tags:
    - configs
    - polybar
- name: copy polybar bottom menu
  template:
    src: config/polybar/{{machine}}/default/bottom.ini.j2
    dest: "{{destination}}/.config/polybar//default/bottom.ini"
  tags:
    - configs
    - polybar
- name: Copy Default Launcher Script
  copy: src=config/polybar/{{machine}}/default/launch.sh dest={{destination}}/.config/polybar/default owner={{user}} mode=0774
  tags:
    - configs
    - polybar
- name: Change scripts permission
  command: "chmod +x {{destination}}/.config/polybar/scripts/{{item}}"
  with_items:
    - gnomato
    - lyrics
    - powermenu
    - translate_lyrics
    - dropbox-isrunning.sh
    - golem-isrunning.sh
    - player-mpris-simple.sh
    - pysense-isrunning.sh
    - nextevent.sh
    - remaining.sh
    - gnomato-log.sh
    - popup-calendar.sh
    - open-calendar.sh
    - check-port
    - pulseaudio-control.sh
    - pulseaudio-input-listener.sh
    - countdown.sh
    - lifeguard.sh
  tags:
    - configs
    - polybar
