---
- name: "[Fedora] Install dependencies for polybar"
  become_user: root
  dnf:
    name:
      - make
      - cmake
      - gcc-c++
      - cairo-devel
      - libcurl-devel
      - alsa-lib-devel
      - libmpd-devel
      - mpc
      - pulseaudio-libs-devel
      - xcb-proto
      - python2-devel
      - libmpdclient
      - libmpdclient-devel
      - wireless-tools
      - wireless-tools-devel
      - xcb-util-devel
      - xcb-util-wm-devel
      - xcb-util-cursor-devel
      - xcb-util-xrm-devel
      - jsoncpp
      - jsoncpp-devel
    state: latest
  when: ansible_distribution == 'Fedora' 
- name: Install lyrics package globally.
  become_user: root
  npm:
    name: lyrics-cli
    global: true
- name: Clone polybar repository
  git:
    repo: 'https://github.com/polybar/polybar.git'
    dest: /tmp/polybar
  when: ansible_distribution == 'Fedora' 
- name: copy polybar build script
  copy: src=build/build-polybar.sh dest=/tmp/polybar owner={{user}} group={{user}} mode=0774
  when: ansible_distribution == 'Fedora' 
- name: Make and Install Polybar
  become_user: root
  command: "/tmp/polybar/build-polybar.sh"
  when: ansible_distribution == 'Fedora' 
- name: Copy Polybar Configs
  copy: src=config/polybar dest={{destination}}/.config owner={{user}} group={{user}}
- name: copy polybar default colors 
  template:
    src: config/polybar/default/colors.ini.j2
    dest: "{{destination}}/.config/polybar/default/colors.ini"
- name: Copy Default Launcher Script
  copy: src=config/polybar/default/launch.sh dest={{destination}}/.config/polybar/default owner={{user}} group={{user}} mode=0774
- name: Change scripts permission
  command: "chmod +x {{destination}}/.config/polybar/scripts/{{item}}"
  with_items:
    - gnomato
    - lyrics
    - powermenu
    - translate_lyrics
    - dropbox-isrunning.sh
    - player-mpris-simple.sh
    - pysense-isrunning.sh
    - nextevent.sh
    - gnomato-log.sh
