---
- name: Install lyrics package globally.
  become_user: root
  npm:
    name: lyrics-cli
    global: true
- name: Copy Rofi Configs
  copy: src=config/rofi dest={{destination}}/.config owner={{user}} group={{user}}
- name: Copy Polybar Configs
  copy: src=config/polybar dest={{destination}}/.config owner={{user}} group={{user}}
- name: Copy Launcher Script
  copy: src=config/polybar/launch.sh dest={{destination}}/.config/polybar owner={{user}} group={{user}} mode=0774
- name: Change scripts permission
  command: "chmod +x {{destination}}/.config/polybar/scripts/{{item}}"
  with_items:
    - gnomato
    - lyrics
    - powermenu
    - translate_lyrics
