---
- name: Creates scripts directory
  file:
    path: "{{destination}}/.scripts/bin"
    state: directory
  tags:
    - scripts
- name: Creates scripts bin directory
  file:
    path: "{{destination}}/.scripts/bin"
    state: directory
  tags:
    - scripts
- name: Copy scripts bin files
  copy:
    src: "scripts/bin/{{item}}"
    dest: "{{destination}}/.scripts/bin"
  tags:
    - scripts
  with_items:
    - applications_menu
    - index-projects
    - init-project
    - open-project
    - wallpaper
    - wallpaper-cli
    - find_attribute
    - find_colors
    - change-java-version
    - create-task
    - print-screen
    - print-screen-selection
    - git-logs-in-json
    - what-is-written-here
- name: Change scripts permission
  command: "chmod +x {{destination}}/.scripts/bin/{{item}}"
  tags:
    - scripts
  with_items:
    - applications_menu
    - index-projects
    - init-project
    - open-project
    - wallpaper
    - wallpaper-cli
    - find_attribute
    - find_colors
    - change-java-version
    - create-task
    - print-screen
    - print-screen-selection
    - git-logs-in-json
    - what-is-written-here
