---
- name: Creates scripts directory
  file:
    path: "{{destination}}/.scripts/bin"
    state: directory
- name: Creates scripts bin directory
  file:
    path: "{{destination}}/.scripts/bin"
    state: directory
- name: Copy scripts bin files
  copy:
    src: "scripts/bin/{{item}}"
    dest: "{{destination}}/.scripts/bin"
  with_items:
    - init-project
    - open-project
- name: Change scripts permission
  command: "chmod +x {{destination}}/.scripts/bin/{{item}}"
  with_items:
    - init-project
    - open-project
