---
- name: "[Fedora] Enable Fedora Copr for Termite"
  become_user: root
  command: "dnf copr enable -y skidnik/termite"
  when: ansible_distribution == 'Fedora'
- name: "[Fedora] Install termite"
  become_user: root
  dnf:
    name:
      - termite
    state: latest
  when: ansible_distribution == 'Fedora'
- name: Creates termite config directory
  file:
    path: "{{destination}}/.config/termite"
    state: directory
- name: copy termite config
  copy: src=config/termite/{{theme}}/config dest={{destination}}/.config/termite/config owner="{{user}}" mode=0664
