---
- name: "[Fedora] Install terminator"
  become_user: root
  dnf:
    name:
      - terminator
    state: latest
  when: ansible_distribution == 'Fedora'
- name: Creates terminator config directory
  file:
    path: "{{destination}}/.config/terminator"
    state: directory
- name: copy terminator config
  copy: src=config/terminator/{{theme}}/config dest={{destination}}/.config/terminator/config owner={{user}} mode=0664
