---
- name: Install Zsh From Negativo
  become_user: root
  dnf:
    name:
      - zsh
    state: latest
- name: Install Oh My Zsh
  command: "sh -c \"$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)\""
