#!/bin/bash

killall conky

cd .config/conky

sleep 1
conky -c baterry &

sleep 1
conky -c cpu &

sleep 1
conky -c file_systems &

sleep 1
conky -c memory &

sleep 1
conky -c network & 

sleep 1
conky -c time &

