---
- set_fact:
    theme_name: Default Theme
    dunst_frame_color: "#00c0ff"
    dunst_background : "#191311"
    dunst_urgency_foreground : "#fbf7f6"
    rofi_background: "#1d2021c5"
    rofi_background_alt: "#035be598"
    rofi_text_color: "#fbf7f6"
    rofi_primary: "#039be5"
    rofi_urgent: "#e53935"
    i3_colors: |
      client.focused          #039be5     #039be5     #0a0710  #000000       #039be5
      client.focused_inactive #039be5     #039be5     #fbf7f6  #000000       #039be5
      client.unfocused        #039be5     #039be5     #fbf7f6  #000000       #039be5
      client.urgent           #039be5     #ff0000     #fbf7f6  #ff0000       #039be5
      client.placeholder      #039be5     #039be5     #fbf7f6  #000000       #039be5
      
      client.background       #039be5

    polybar_colors: |
      ;; Active Colors
      bg = #c90a0710
      fg = #fbf7f6
      ac = #00c0ff
      mf = #fbf7f6
      
      ;; Bars
      bi = #00c0ff
      be = #e53935
      bf = #43a047
      bn = #43a047
      bm = #fdd835
      bd = #e53935
      
      trans = #00000000
      white = #FFFFFF
      black = #000000

  when: theme == "default"
