# Exports
export EDITOR=nvim
export KUBE_EDITOR=vim

export PATH="/opt/java/bin:$PATH"
export PATH="$PATH:/opt/node/bin"
export PATH="$PATH:/opt/flutter/bin"
export PATH="$PATH:/opt/gradle/bin"
export PATH="$PATH:/opt/maven/bin"
export PATH="$PATH:/opt/istio/bin"
export PATH="$PATH:/opt/kafka/bin"
export PATH="$PATH:$HOME/.local/bin"
export PATH="$PATH:$HOME/.cargo/bin"
export PATH="$PATH:$HOME/go/bin"
export PATH="$PATH:$HOME/.scripts/bin"
export PATH="$PATH:/snap/bin"

# Aliases
alias k=kubectl

# Screen functions
home_screen_layout() {
  xrandr --output eDP-1  --auto --output HDMI-1-4 --primary --auto --left-of eDP-1 --output DP-1 --auto --above HDMI-1-4
}

clone_hdmi_screen_layout() {
  xrandr --output eDP-1 --primary --auto --output HDMI-1-4 --auto
}

disable_external_monitors() {
  xrandr --output eDP-1 --primary --auto --output HDMI-1-4 --off --output DP-1 --off
}

# Docker Functions
clear_containers() {
	docker stop $(docker ps -a -q)
	docker rm $(docker ps -a -q)
}

clear_images() {
	docker rmi -f $(docker images -a -q)
}

# Open Mapper
open_private() {
  sudo cryptsetup -v luksOpen /dev/sda2 private
}

open_secret() {
  sudo cryptsetup -v luksOpen /dev/sda1 secret
}

open_external() {
  sudo cryptsetup -v luksOpen /dev/sdc2 external
}

# Rust Configuration
[[ -s "$HOME/.cargo/env" ]] && source "$HOME/.cargo/env"

# RVM configuration
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"

# load fzf
[[ -s ~/.fzf.zsh ]] && source ~/.fzf.zsh

# Load private resources
[[ -s "$HOME/.zsh_private" ]] && source "$HOME/.zsh_private"
