# Exports
export EDITOR=nvim

export PATH="$PATH:~/.pkgs/node/bin"

# Docker Functions
clear_containers() {
	docker stop $(docker ps -a -q)
	docker rm $(docker ps -a -q)
}

clear_images() {
	docker rmi -f $(docker images -a -q)
}
